### ISSUE TITLE
Minimizing the window crashes the game

### ISSUE THREAD

**Issue by BTCTaras** [Lemmmy/JRogue#104]
```
java.lang.IllegalStateException: Frame buffer couldn't be constructed: incomplete attachment
	at com.badlogic.gdx.graphics.glutils.GLFrameBuffer.build(GLFrameBuffer.java:255)
	at com.badlogic.gdx.graphics.glutils.FrameBuffer.<init>(FrameBuffer.java:75)
	at com.badlogic.gdx.graphics.glutils.FrameBuffer.<init>(FrameBuffer.java:57)
	at jr.rendering.GameAdapter.resize(GameAdapter.java:179)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Graphics$1.invoke(Lwjgl3Graphics.java:71)
	at org.lwjgl.glfw.GLFWFramebufferSizeCallbackI.callback(GLFWFramebufferSizeCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3037)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at jr.JRogue.<init>(JRogue.java:119)
	at jr.JRogue.main(JRogue.java:242)
```

**Comment by Lemmmy** [comment]
Let me know if 57f4946 fixes this (checkout the `fix/incomplete-attachment-minimise` branch).
