### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by demhydraz** [Lemmmy/JRogue#4]
**OS:** Linux (amd64)
**Java:** 1.8.0_112
**Trace:**
```
java.lang.NullPointerException
	at pw.lemmmy.jrogue.dungeon.Dungeon.unserialise(Dungeon.java:177)
	at pw.lemmmy.jrogue.dungeon.Dungeon.load(Dungeon.java:132)
	at pw.lemmmy.jrogue.JRogue.<init>(JRogue.java:25)
	at pw.lemmmy.jrogue.JRogue.main(JRogue.java:83)

```

_i swear to god_

**Comment by Lemmmy** [comment]
Fixed
