### ISSUE TITLE
ConcurrentModificationException in LWJGL Application Thread

### ISSUE THREAD

**Issue by demhydraz** [Lemmmy/JRogue#5]
Crash reporter when?

```
Exception in thread "LWJGL Application" java.util.ConcurrentModificationException
    at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
    at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
    at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
    at java.util.Iterator.forEachRemaining(Iterator.java:116)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at pw.lemmmy.jrogue.dungeon.entities.EntityChest.onKick(EntityChest.java:67)
    at pw.lemmmy.jrogue.dungeon.entities.Entity.kick(Entity.java:240)
    at pw.lemmmy.jrogue.dungeon.entities.actions.ActionKick.entityKick(ActionKick.java:56)
    at pw.lemmmy.jrogue.dungeon.entities.actions.ActionKick.execute(ActionKick.java:47)
    at pw.lemmmy.jrogue.dungeon.entities.EntityTurnBased.move(EntityTurnBased.java:41)
    at pw.lemmmy.jrogue.dungeon.Dungeon.turn(Dungeon.java:466)
    at pw.lemmmy.jrogue.dungeon.entities.Player$2.onResponse(Player.java:621)
    at pw.lemmmy.jrogue.dungeon.Prompt.respond(Prompt.java:72)
    at pw.lemmmy.jrogue.dungeon.Dungeon.promptRespond(Dungeon.java:383)
    at pw.lemmmy.jrogue.rendering.gdx.GameInputProcessor.keyTyped(GameInputProcessor.java:196)
    at com.badlogic.gdx.InputMultiplexer.keyTyped(InputMultiplexer.java:84)
    at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:318)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)
```
[here](https://hydraz.club/txt/log) is what log was still in my terminal

**Comment by Lignumm** [comment]
Well, either 58ad90de27242b626919000f436d42d70305a7d6 didn't work, or you're out of date.

**Comment by demhydraz** [comment]
rip
