### ISSUE TITLE
NPE on dungeon load

### ISSUE THREAD

**Issue by Lignumm** [Lemmmy/JRogue#6]
**OS:** Linux (amd64)
**Java:** 1.8.0_112
**Trace:**
```
java.lang.NullPointerException
	at pw.lemmmy.jrogue.dungeon.Dungeon.unserialise(Dungeon.java:188)
	at pw.lemmmy.jrogue.dungeon.Dungeon.load(Dungeon.java:132)
	at pw.lemmmy.jrogue.JRogue.<init>(JRogue.java:25)
	at pw.lemmmy.jrogue.JRogue.main(JRogue.java:83)

```

After closing the game and re-opening it, this happened. Reopening it again worked flawlessly.

**Comment by Lignumm** [comment]
Seems to be #4, except you fixed that.

**Comment by Lemmmy** [comment]
I added a return in 7eaadf7 which is probably why you were running into that NPE still despite me adding a handler for it
